In [1]:
import pandas as pd

In [2]:
! pip install pandas openpyxl

Requirement already satisfied: pandas in /home/hhbach/anaconda3/lib/python3.11/site-packages (2.1.4)
Requirement already satisfied: openpyxl in /home/hhbach/anaconda3/lib/python3.11/site-packages (3.0.10)
Requirement already satisfied: numpy<2,>=1.23.2 in /home/hhbach/anaconda3/lib/python3.11/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/hhbach/anaconda3/lib/python3.11/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /home/hhbach/anaconda3/lib/python3.11/site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /home/hhbach/anaconda3/lib/python3.11/site-packages (from pandas) (2023.3)
Requirement already satisfied: et_xmlfile in /home/hhbach/anaconda3/lib/python3.11/site-packages (from openpyxl) (1.1.0)
Requirement already satisfied: six>=1.5 in /home/hhbach/anaconda3/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [3]:
! ls

cambodia.xlsx  co1-laos.fa  cytb-camb.fa  cytob-vn.fa  nb.ipynb
co1-camb.fa    co1-vn.fa    cytb-laos.fa  laos.xlsx    vn.xlsx

In [1]:
import pandas as pd

# Read the Excel file
df = pd.read_excel("vn.xlsx", engine="openpyxl")
df

,Tên thông thường,Tên khoa học,Tên tiếng Anh,Kiểu gen,COI,Cytb,Phân hạng IUCN (2008 v3.1),Link IUCN,Phân hạng Danh lục Đỏ Việt Nam (2007),Mô tả,Arkive,Encyclopedia of Life,gbif
0,Chồn bay (Cầy bay),Galeopterus variegatus,Sunda flying lemur,full mt,AF460846,AF460846,LC,http://www.iucnredlist.org/details/41502/0,EN A1c C1,"Đầu rộng, tai ngắn tròn hoặc tù. Mắt to, màu n...",http://www.arkive.org/malayan-colugo/galeopter...,http://eol.org/pages/1040858/overview,http://www.gbif.org/species/2432087
1,Dơi ngựa lớn,Pteropus vampyrus,Large flying fox,full mt,NC_026542,NC_026542,NT,http://www.iucnredlist.org/details/18766/0,NaN,Dơi ngựa lớn là loài dơi lớn nhất trong họ Dơi...,http://www.arkive.org/large-flying-fox/pteropu...,http://eol.org/pages/327300/overview,http://www.gbif.org/species/5218644
2,Cu li lớn,Nycticebus bengalensis,Bengal loris,full mt,KC977312,KC977312,VU A2acd+3cd+4acd,http://www.iucnredlist.org/details/39758/0,"VU A1c,d","Cỡ nhỏ. Dài thân: 260 - 310mm, dài đuôi: 19 - ...",http://www.arkive.org/bengal-slow-loris/nyctic...,http://eol.org/pages/4454392/overview,http://www.gbif.org/species/4267329
3,Cu li nhỏ,Nycticebus pygmaeus,Pygmy loris,"cytb, COI",KJ862196 barcode,AY687893,VU A2cd,http://www.iucnredlist.org/details/14941/0,"VU A1c,d",Cỡ nhỏ hơn cu li lớn. Dài thân: 286mm + 18 dài...,http://www.arkive.org/pygmy-loris/nycticebus-p...,http://eol.org/pages/326539/overview,http://www.gbif.org/species/2436628
4,Voọc chà vá chân xám,Pygathrix cinerea,Gray-shanked douc,full mt,NC_018063,NC_018063,CR A2cd+3cd+4cd,http://www.iucnredlist.org/details/39827/0,CR A1c B2b D,"Hình dạng, kích thước và màu sắc tương tự như ...",http://www.arkive.org/grey-shanked-douc/pygath...,http://eol.org/pages/7252447/overview,http://www.gbif.org/species/4267165
...,...,...,...,...,...,...,...,...,...,...,...,...,...
134,Rùa núi vàng,Indotestudo elongata,Elongated Tortoise,full mt,DQ656607,DQ656607,EN A1cd+2cd,http://www.iucnredlist.org/details/10824/0,EN A1d+2d,"Cơ thể cỡ trung bình, chiều dài mai khoảng 275...",http://www.arkive.org/elongated-tortoise/indot...,http://eol.org/pages/1056225/overview,http://www.gbif.org/species/2441437
135,Rùa núi viền,Manouria impressa,Impressed Tortoise,"Cytb, COI, full mt","NC_011815, EF661586","NC_011815, EF661586","VU A1acd, B1+2acd",http://www.iucnredlist.org/details/12775/0,"VU A1c,d","Cỡ trung bình, chiều dài mai khoảng 180 - 206m...",http://www.arkive.org/impressed-tortoise/manou...,http://eol.org/pages/1055882/overview,http://www.gbif.org/species/2441823
136,Cá sấu hoa cà,Crocodylus porosus,Salt-water Crocodile,full mt,DQ273698,DQ273698,LR/lc,http://www.iucnredlist.org/details/5668/0,EW,"Cá sấu hoa cà là loài bò sát cỡ lớn, khác biệt...",http://www.arkive.org/saltwater-crocodile/croc...,http://eol.org/pages/454963/overview,http://www.gbif.org/species/2441333
137,Cá sấu nước ngọt (Cá sấu Xiêm),Crocodylus siamensis,Siamese Crocodile,full mt,NC_008795,NC_008795,CR A2cd,http://www.iucnredlist.org/details/5671/0,"CR A1c,d","Cỡ lớn, chiều dài cơ thể khoảng 2,2 - 2,3m (tr...",http://www.arkive.org/siamese-crocodile/crocod...,http://eol.org/pages/795275/overview,http://www.gbif.org/species/2441348
138,Cá cóc Tam Đảo,Paramesotriton deloustali,Tam Dao Salamander,full mt,EU880327,EU880327,"VU B2ab(iii,v)",http://www.iucnredlist.org/details/16129/0,"EN B1+ 2b,c,d","Cá cóc có thân hình thuôn dài, hơi dẹt từ trên...",http://www.arkive.org/vietnamese-salamander/pa...,http://eol.org/pages/330901/overview,http://www.gbif.org/species/2431843

In [5]:
df.head()

,Tên thông thường,Tên khoa học,Tên tiếng Anh,Kiểu gen,COI,Cytb,Phân hạng IUCN (2008 v3.1),Link IUCN,Phân hạng Danh lục Đỏ Việt Nam (2007),Mô tả,Arkive,Encyclopedia of Life,gbif
0,Chồn bay (Cầy bay),Galeopterus variegatus,Sunda flying lemur,full mt,AF460846,AF460846,LC,http://www.iucnredlist.org/details/41502/0,EN A1c C1,"Đầu rộng, tai ngắn tròn hoặc tù. Mắt to, màu n...",http://www.arkive.org/malayan-colugo/galeopter...,http://eol.org/pages/1040858/overview,http://www.gbif.org/species/2432087
1,Dơi ngựa lớn,Pteropus vampyrus,Large flying fox,full mt,NC_026542,NC_026542,NT,http://www.iucnredlist.org/details/18766/0,NaN,Dơi ngựa lớn là loài dơi lớn nhất trong họ Dơi...,http://www.arkive.org/large-flying-fox/pteropu...,http://eol.org/pages/327300/overview,http://www.gbif.org/species/5218644
2,Cu li lớn,Nycticebus bengalensis,Bengal loris,full mt,KC977312,KC977312,VU A2acd+3cd+4acd,http://www.iucnredlist.org/details/39758/0,"VU A1c,d","Cỡ nhỏ. Dài thân: 260 - 310mm, dài đuôi: 19 - ...",http://www.arkive.org/bengal-slow-loris/nyctic...,http://eol.org/pages/4454392/overview,http://www.gbif.org/species/4267329
3,Cu li nhỏ,Nycticebus pygmaeus,Pygmy loris,"cytb, COI",KJ862196 barcode,AY687893,VU A2cd,http://www.iucnredlist.org/details/14941/0,"VU A1c,d",Cỡ nhỏ hơn cu li lớn. Dài thân: 286mm + 18 dài...,http://www.arkive.org/pygmy-loris/nycticebus-p...,http://eol.org/pages/326539/overview,http://www.gbif.org/species/2436628
4,Voọc chà vá chân xám,Pygathrix cinerea,Gray-shanked douc,full mt,NC_018063,NC_018063,CR A2cd+3cd+4cd,http://www.iucnredlist.org/details/39827/0,CR A1c B2b D,"Hình dạng, kích thước và màu sắc tương tự như ...",http://www.arkive.org/grey-shanked-douc/pygath...,http://eol.org/pages/7252447/overview,http://www.gbif.org/species/4267165

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 139 entries, 0 to 138
Data columns (total 13 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Tên thông thường                       139 non-null    object
 1   Tên khoa học                           139 non-null    object
 2   Tên tiếng Anh                          139 non-null    object
 3   Kiểu gen                               126 non-null    object
 4   COI                                    86 non-null     object
 5   Cytb                                   127 non-null    object
 6   Phân hạng IUCN (2008 v3.1)             133 non-null    object
 7   Link IUCN                              131 non-null    object
 8   Phân hạng Danh lục Đỏ Việt Nam (2007)  113 non-null    object
 9   Mô tả                                  100 non-null    object
 10  Arkive                                 100 non-null    object
 11  Encyclopedia of Life                   139 non-null    object
 12  gbif                                   135 non-null    object
dtypes: object(13)
memory usage: 14.2+ KB